### ISSUE TITLE
A better job?

### ISSUE THREAD

**Issue by ryantheleach** [randombyte-developer/empty-server-stopper#1]
If you think you can do a better job, or want to add features, feel free to fork 
https://github.com/ryantheleach/emptyservercommands
Under any license you choose, or start your own from scratch.

I'd sooner not support (This plugin idea/request) if someone else was willing to continue to provide updates.

**Comment by randombyte-developer** [comment]
Hm, my plugin is very simplistic, minimalistic.
Yeah, I will expand mine into the direction your plugin goes. I don't fork your project because I would like to develop in Kotlin. I will also create a new repo because of the new name. Can I use the same plugin id?

**Comment by ryantheleach** [comment]
Sorry I missed this reply at first, I'd avoid using the same plugin id but feel free if you want to, I don't really see people having both of the plugins installed at the same time, unless it's going to cause problems on Ore it should be fine.

Updates? just API/bugs is what I was thinking.

**Comment by randombyte-developer** [comment]
So, you will never publish your plugin? Then I would use the same plugin name and your id but hyphen seperated. Otherwise I would change the name to avoid confusion in the forums. 
Yes, I'll support this plugin like my others.

**Comment by ryantheleach** [comment]
If your plugin covers everything that mine did, I won't post on Ore, and won't give it it's own topic. but it's already listed on the plugin request, and my github.

**Comment by randombyte-developer** [comment]
https://github.com/randombyte-developer/empty-server-commands
Well, I simply renamed the plugin and added the possibility to execute commands defined in the config.

**Comment by ryantheleach** [comment]
I wasn't sure either, the thought I had was if it was a minigames server, and that if 1 person was trying to start the game, with no one joining for a certain amount of time maybe you wanted them booted to lobby?

IDK, it's probably not necessary, I just hate hard coding constants into small plugins like this, then have to introduce a variable later on because someone wants it as a feature.

**Comment by randombyte-developer** [comment]
Screw it. I'll just add that too.

**Comment by randombyte-developer** [comment]
I'll delete this repo soon.
